name: phpBB Extension CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.0']
        db-type: [sqlite]

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, pdo_sqlite
          coverage: none

      - name: Clone phpBB
        run: git clone --depth=1 --branch=3.2.x https://github.com/phpbb/phpbb.git phpbb

      - name: Set up phpBB
        run: |
          cd phpbb
          composer install --no-interaction --no-progress
          mkdir -p ext/threedi
          cp -r ../* ext/threedi/tpotm

      - name: Run EPV
        run: |
          cd phpbb
          composer require phpbb/epv:dev-master --dev --no-interaction --ignore-platform-reqs
          vendor/bin/EPV.php run --dir="ext/threedi/tpotm" || true

      - name: Run PHP Lint
        run: find . -name '*.php' -not -path "./phpbb/vendor/*" -exec php -l {} \;

      - name: Validate composer.json
        run: composer validate --strict
