name: PHPBB Extension CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.3', '7.4', '8.0', '8.1', '8.2']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, pdo, pdo_mysql, pdo_pgsql, sqlite, intl
        coverage: none

    - name: Install unzip and git
      run: sudo apt-get update && sudo apt-get install -y unzip git

    - name: Download phpBB 3.3.15 release zip
      run: |
        curl -L -o phpbb.zip https://github.com/phpbb/phpbb/archive/refs/tags/release-3.3.15.zip
        unzip phpbb.zip
        mv phpbb-release-3.3.15 phpbb

    - name: Copy extension into phpBB ext directory
      run: |
        mkdir -p phpbb/ext/threedi/tpotm
        rsync -av --exclude='phpbb' --exclude='.github' --exclude='.git' ./ phpbb/ext/threedi/tpotm/

    - name: Install phpBB dependencies with Composer
      run: composer install --no-interaction --no-progress --ignore-platform-reqs
      working-directory: phpbb

    - name: Run EPV (Extension Pre Validator)
      run: |
        composer require phpbb/epv:dev-master --dev --ignore-platform-reqs
        vendor/bin/EPV.php run --dir=ext/threedi/tpotm/
      working-directory: phpbb

    - name: Run PHP CodeSniffer
      run: |
        if [ -f "phpcs.xml" ]; then
          composer global require "squizlabs/php_codesniffer=*"
          ~/.composer/vendor/bin/phpcs --standard=phpcs.xml .
        else
          echo "No phpcs.xml found, skipping code sniff."
        fi
      working-directory: phpbb/ext/threedi/tpotm
