name: phpBB Extension CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.0']
        db-type: [sqlite]

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, pdo_sqlite
          coverage: none

      - name: Clone phpBB repository
        run: git clone --depth=1 --branch=3.2.x https://github.com/phpbb/phpbb.git phpbb

      - name: Copy extension into phpBB ext directory
        run: |
          mkdir -p phpbb/ext/threedi
          cp -r ./* phpbb/ext/threedi/tpotm

      - name: Install EPV tool for phpBB
        run: |
          cd phpbb
          composer require phpbb/epv:dev-master --dev --no-interaction --ignore-platform-reqs

      - name: Run Extension Pre Validator (EPV)
        run: |
          cd phpbb
          vendor/bin/EPV.php run --dir="ext/threedi/tpotm" || true

      - name: Install extension dependencies via Composer
        run: composer install --no-interaction --no-progress --working-dir=phpbb/ext/threedi/tpotm

      - name: Validate extension composer.json
        run: composer validate --strict --no-interaction --working-dir=phpbb/ext/threedi/tpotm

      - name: Run PHP syntax check
        run: find phpbb/ext/threedi/tpotm -name '*.php' -exec php -l {} \;
