name: PHPBB Extension CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1', '8.2']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, pdo, pdo_mysql, pdo_pgsql, sqlite, intl
        coverage: none

    - name: Install Git
      run: sudo apt-get update && sudo apt-get install -y git

    - name: Clone phpBB repository and checkout tag 3.3.15
      run: |
        git clone --depth=1 https://github.com/phpbb/phpbb.git phpbb
        cd phpbb
        git checkout tags/3.3.15

    - name: Copy extension into phpBB ext directory
      run: |
        mkdir -p phpbb/ext/threedi/tpotm
        rsync -av --exclude='phpbb' --exclude='.github' --exclude='.git' ./ phpbb/ext/threedi/tpotm/

    - name: Install phpBB dependencies
      run: |
        cd phpbb
        composer install --no-interaction --no-progress --ignore-platform-reqs

    - name: Run EPV (Extension Pre Validator)
      run: |
        cd phpbb
        composer require phpbb/epv:dev-master --dev --ignore-platform-reqs
        vendor/bin/EPV.php run --dir=ext/threedi/tpotm/

    - name: Run PHP CodeSniffer
      run: |
        cd phpbb/ext/threedi/tpotm
        if [ -f "phpcs.xml" ]; then
          composer global require "squizlabs/php_codesniffer=*"
          ~/.composer/vendor/bin/phpcs --standard=phpcs.xml .
        else
          echo "No phpcs.xml found, skipping code sniff."
        fi
